import Banner from "components/Banner";
import Header from "components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel-Bois</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      {/* Section - Small Cards */}
      <main className="border-2 max-w-7xl mx-auto px-8 sm:px-16">
        <section className="border-2 border-red-400 pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* Pull some data from a server - API Endpoints */}
          
        </section>
      </main>
    </>
  );
}
